#!/usr/bin/env node
/**
 * 全面翻译products.json中的剩余中文内容
 */

const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'data', 'anlogic', 'products.json');
let content = fs.readFileSync(filePath, 'utf8');

// 中文到英文的映射
const translations = {
  // 常用词汇和短语
  '是': 'is',
  '的': '',
  '和': 'and',
  '或': 'or',
  '等': 'and other',
  '该': 'This',
  '采用': 'adopts',
  '具有': 'has',
  '广泛': 'widely',
  '用于': 'used for',
  '包括': 'including',
  '帮助': 'helps',
  '实现': 'achieve',
  '快速': 'quickly',
  '客户': 'customers',
  '提供': 'provides',
  '支持': 'support',
  '需要': 'requires',
  '可以': 'can',
  '进行': 'perform',
  '通过': 'through',
  '使用': 'using',
  '适合': 'suitable for',
  '应用': 'applications',
  '领域': 'fields',
  '设备': 'equipment',
  '技术': 'technology',
  '性能': 'performance',
  '可靠性': 'reliability',
  '工艺': 'process',
  '先进': 'advanced',
  '优异': 'excellent',
  '丰富': 'rich',
  '详细': 'detailed',
  '免费': 'free',
  '量产': 'mass production',
  '开发': 'development',
  '产品': 'product',
  '工具': 'tools',
  '软件': 'software',
  '库': 'library',
  '设计': 'design',
  '参考': 'reference',
  '数据': 'data',
  '存储': 'storage',
  '缓存': 'cache',
  '配置': 'configuration',
  '管理': 'management',
  '控制': 'control',
  '复位': 'reset',
  '电源': 'power',
  '时序': 'timing',
  '逻辑': 'logic',
  '胶合': 'glue',
  '电平': 'level',
  '转换': 'translation',
  '扩展': 'expansion',
  '接口': 'interface',
  '总线': 'bus',
  '协议': 'protocol',
  '通信': 'communication',
  '网络': 'network',
  '视频': 'video',
  '图像': 'image',
  '处理': 'processing',
  '加速': 'acceleration',
  '计算': 'computing',
  '推理': 'inference',
  '学习': 'learning',
  '训练': 'training',
  '识别': 'recognition',
  '检测': 'detection',
  '跟踪': 'tracking',
  '定位': 'positioning',
  '测量': 'measurement',
  '采集': 'acquisition',
  '分析': 'analysis',
  '监控': 'monitoring',
  '显示': 'display',
  '驱动': 'driver',
  '照明': 'lighting',
  '充电': 'charging',
  '供电': 'power supply',
  '电池': 'battery',
  '节能': 'energy saving',
  '高效': 'efficient',
  '低功耗': 'low power',
  '静态': 'static',
  '动态': 'dynamic',
  '功耗': 'power consumption',
  '温度': 'temperature',
  '电压': 'voltage',
  '电流': 'current',
  '频率': 'frequency',
  '速率': 'speed',
  '带宽': 'bandwidth',
  '延迟': 'latency',
  '抖动': 'jitter',
  '噪声': 'noise',
  '干扰': 'interference',
  '保护': 'protection',
  '隔离': 'isolation',
  '滤波': 'filtering',
  '放大': 'amplification',
  '调制': 'modulation',
  '解调': 'demodulation',
  '编码': 'encoding',
  '解码': 'decoding',
  '压缩': 'compression',
  '解压': 'decompression',
  '加密': 'encryption',
  '解密': 'decryption',
  '验证': 'verification',
  '测试': 'testing',
  '调试': 'debugging',
  '仿真': 'simulation',
  '建模': 'modeling',
  '优化': 'optimization',
  '评估': 'evaluation',
  '验证': 'validation',
  '确认': 'confirmation',
  '检查': 'checking',
  '监测': 'monitoring',
  '报警': 'alarm',
  '记录': 'recording',
  '存储': 'storage',
  '备份': 'backup',
  '恢复': 'recovery',
  '更新': 'update',
  '升级': 'upgrade',
  '维护': 'maintenance',
  '维修': 'repair',
  '更换': 'replacement',
  '替代': 'alternative',
  '兼容': 'compatible',
  '通用': 'universal',
  '标准': 'standard',
  '规范': 'specification',
  '认证': 'certification',
  '授权': 'authorization',
  '许可': 'license',
  '专利': 'patent',
  '商标': 'trademark',
  '版权': 'copyright',
  '保密': 'confidential',
  '安全': 'security',
  '可靠': 'reliable',
  '稳定': 'stable',
  '耐用': 'durable',
  '坚固': 'robust',
  '紧凑': 'compact',
  '轻便': 'lightweight',
  '便携': 'portable',
  '灵活': 'flexible',
  '可扩展': 'scalable',
  '可配置': 'configurable',
  '可编程': 'programmable',
  '可升级': 'upgradable',
  '可维护': 'maintainable',
  '易用': 'easy to use',
  '友好': 'user-friendly',
  '直观': 'intuitive',
  '清晰': 'clear',
  '简洁': 'concise',
  '完整': 'complete',
  '全面': 'comprehensive',
  '专业': 'professional',
  '专注': 'dedicated',
  '专家': 'expert',
  '团队': 'team',
  '服务': 'service',
  '咨询': 'consulting',
  '建议': 'advice',
  '方案': 'solution',
  '解决': 'solve',
  '问题': 'problem',
  '故障': 'failure',
  '错误': 'error',
  '异常': 'abnormal',
  '警告': 'warning',
  '提示': 'hint',
  '说明': 'description',
  '指南': 'guide',
  '手册': 'manual',
  '文档': 'documentation',
  '资料': 'materials',
  '信息': 'information',
  '详情': 'details',
  '摘要': 'summary',
  '概述': 'overview',
  '介绍': 'introduction',
  '背景': 'background',
  '历史': 'history',
  '现状': 'current status',
  '趋势': 'trend',
  '前景': 'prospect',
  '未来': 'future',
  '发展': 'development',
  '进步': 'progress',
  '创新': 'innovation',
  '突破': 'breakthrough',
  '成就': 'achievement',
  '成功': 'success',
  '成果': 'result',
  '效果': 'effect',
  '影响': 'impact',
  '作用': 'role',
  '价值': 'value',
  '意义': 'significance',
  '重要性': 'importance',
  '必要性': 'necessity',
  '优势': 'advantage',
  '劣势': 'disadvantage',
  '特点': 'feature',
  '特性': 'characteristic',
  '功能': 'function',
  '用途': 'usage',
  '用法': 'usage',
  '操作': 'operation',
  '步骤': 'steps',
  '流程': 'process',
  '方法': 'method',
  '方式': 'way',
  '模式': 'mode',
  '类型': 'type',
  '种类': 'category',
  '分类': 'classification',
  '等级': 'level',
  '标准': 'standard',
  '规格': 'specification',
  '参数': 'parameter',
  '指标': 'indicator',
  '数据': 'data',
  '信息': 'information',
  '内容': 'content',
  '项目': 'item',
  '条目': 'entry',
  '列表': 'list',
  '表格': 'table',
  '图表': 'chart',
  '图形': 'graph',
  '图像': 'image',
  '图片': 'picture',
  '照片': 'photo',
  '视频': 'video',
  '音频': 'audio',
  '文件': 'file',
  '目录': 'directory',
  '路径': 'path',
  '地址': 'address',
  '位置': 'location',
  '方向': 'direction',
  '距离': 'distance',
  '长度': 'length',
  '宽度': 'width',
  '高度': 'height',
  '深度': 'depth',
  '厚度': 'thickness',
  '直径': 'diameter',
  '半径': 'radius',
  '面积': 'area',
  '体积': 'volume',
  '容量': 'capacity',
  '重量': 'weight',
  '质量': 'quality',
  '密度': 'density',
  '浓度': 'concentration',
  '纯度': 'purity',
  '精度': 'accuracy',
  '准度': 'precision',
  '分辨率': 'resolution',
  '灵敏度': 'sensitivity',
  '响应': 'response',
  '反应': 'reaction',
  '反馈': 'feedback',
  '补偿': 'compensation',
  '校正': 'calibration',
  '调整': 'adjustment',
  '调节': 'regulation',
  '控制': 'control',
  '管理': 'management',
  '监控': 'monitoring',
  '监督': 'supervision',
  '检查': 'inspection',
  '检测': 'detection',
  '测量': 'measurement',
  '计量': 'metering',
  '计数': 'counting',
  '统计': 'statistics',
  '计算': 'calculation',
  '运算': 'operation',
  '处理': 'processing',
  '分析': 'analysis',
  '综合': 'synthesis',
  '总结': 'summary',
  '报告': 'report',
  '汇报': 'presentation',
  '展示': 'display',
  '演示': 'demonstration',
  '示例': 'example',
  '实例': 'instance',
  '案例': 'case',
  '样板': 'sample',
  '模板': 'template',
  '模型': 'model',
  '模式': 'pattern',
  '范式': 'paradigm',
  '风格': 'style',
  '形式': 'form',
  '方式': 'manner',
  '方法': 'approach',
  '技术': 'technique',
  '技能': 'skill',
  '技巧': 'tip',
  '诀窍': 'knack',
  '秘密': 'secret',
  '关键': 'key',
  '核心': 'core',
  '重点': 'focus',
  '要点': 'main point',
  '难点': 'difficulty',
  '疑点': 'doubt',
  '问题': 'question',
  '答案': 'answer',
  '解答': 'solution',
  '解释': 'explanation',
  '说明': 'instruction',
  '描述': 'description',
  '表达': 'expression',
  '表示': 'representation',
  '显示': 'display',
  '指示': 'indication',
  '指出': 'point out',
  '提示': 'prompt',
  '提醒': 'reminder',
  '警告': 'warning',
  '注意': 'attention',
  '小心': 'careful',
  '谨慎': 'cautious',
  '严格': 'strict',
  '严肃': 'serious',
  '认真': 'serious',
  '仔细': 'careful',
  '详细': 'detailed',
  '具体': 'specific',
  '明确': 'clear',
  '清楚': 'clear',
  '明白': 'understand',
  '了解': 'understand',
  '知道': 'know',
  '认识': 'recognize',
  '熟悉': 'familiar',
  '掌握': 'master',
  '精通': 'proficient',
  '擅长': 'good at',
  '善于': 'skilled in',
  '能力': 'ability',
  '才能': 'talent',
  '才华': 'talent',
  '技能': 'skill',
  '技巧': 'technique',
  '经验': 'experience',
  '经历': 'experience',
  '阅历': 'experience',
  '知识': 'knowledge',
  '学问': 'learning',
  '学术': 'academics',
  '理论': 'theory',
  '实践': 'practice',
  '实际': 'actual',
  '事实': 'fact',
  '真实': 'real',
  '现实': 'reality',
  '现状': 'current situation',
  '情况': 'situation',
  '状况': 'condition',
  '状态': 'state',
  '情形': 'circumstance',
  '环境': 'environment',
  '背景': 'background',
  '条件': 'condition',
  '前提': 'prerequisite',
  '基础': 'foundation',
  '根本': 'fundamental',
  '基本': 'basic',
  '根本': 'root',
  '本质': 'essence',
  '实质': 'substance',
  '性质': 'nature',
  '属性': 'attribute',
  '特征': 'feature',
  '特点': 'characteristic',
  '特色': 'characteristic',
  '特殊': 'special',
  '特别': 'especially',
  '尤其': 'especially',
  '格外': 'especially',
  '非常': 'very',
  '十分': 'very',
  '相当': 'quite',
  '比较': 'relatively',
  '相对': 'relative',
  '绝对': 'absolute',
  '完全': 'completely',
  '彻底': 'thoroughly',
  '全面': 'comprehensively',
  '充分': 'fully',
  '充足': 'sufficient',
  '足够': 'enough',
  '丰富': 'abundant',
  '充裕': 'ample',
  '大量': 'large amount',
  '许多': 'many',
  '很多': 'many',
  '不少': 'quite a few',
  '很多': 'a lot',
  '大量': 'massive',
  '大批': 'large batch',
  '大宗': 'bulk',
  '大额': 'large amount',
  '大额': 'substantial',
  '巨额': 'huge amount',
  '庞大': 'huge',
  '巨大': 'enormous',
  '极大': 'extremely large',
  '很大': 'very large',
  '较大': 'relatively large',
  '更大': 'larger',
  '最大': 'largest',
  '最小': 'smallest',
  '最少': 'least',
  '最多': 'most',
  '最佳': 'best',
  '最好': 'best',
  '最优': 'optimal',
  '最差': 'worst',
  '最坏': 'worst',
  '最糟': 'worst',
  '最快': 'fastest',
  '最慢': 'slowest',
  '最高': 'highest',
  '最低': 'lowest',
  '最强': 'strongest',
  '最弱': 'weakest',
  '最新': 'latest',
  '最旧': 'oldest',
  '最早': 'earliest',
  '最晚': 'latest',
  '最先': 'first',
  '最后': 'last',
  '最终': 'final',
  '最初': 'initial',
  '开始': 'start',
  '结束': 'end',
  '完成': 'complete',
  '做完': 'finish',
  '做好': 'do well',
  '做到': 'achieve',
  '达成': 'achieve',
  '达到': 'reach',
  '到达': 'arrive',
  '来到': 'come',
  '前往': 'go',
  '出去': 'go out',
  '进入': 'enter',
  '进去': 'go in',
  '回来': 'come back',
  '回去': 'go back',
  '返回': 'return',
  '离开': 'leave',
  '出发': 'depart',
  '到达': 'arrive',
  '抵达': 'reach',
  '停留': 'stay',
  '保持': 'maintain',
  '持续': 'continue',
  '继续': 'continue',
  '连续': 'continuous',
  '不断': 'continuously',
  '不停': 'non-stop',
  '一直': 'always',
  '始终': 'always',
  '永远': 'forever',
  '永久': 'permanent',
  '长期': 'long-term',
  '短期': 'short-term',
  '暂时': 'temporary',
  '临时': 'temporary',
  '瞬间': 'instant',
  '立刻': 'immediately',
  '立即': 'immediately',
  '马上': 'right away',
  '赶紧': 'hurry',
  '赶快': 'quickly',
  '快点': 'faster',
  '慢点': 'slower',
  '逐渐': 'gradually',
  '渐渐': 'gradually',
  '逐步': 'step by step',
  '慢慢': 'slowly',
  '缓慢': 'slow',
  '迅速': 'rapid',
  '快速': 'fast',
  '高速': 'high-speed',
  '加速': 'accelerate',
  '减速': 'decelerate',
  '停止': 'stop',
  '暂停': 'pause',
  '中断': 'interrupt',
  '继续': 'resume',
  '恢复': 'restore',
  '还原': 'restore',
  '返回': 'return',
  '后退': 'retreat',
  '前进': 'advance',
  '进步': 'progress',
  '进展': 'progress',
  '发展': 'develop',
  '变化': 'change',
  '改变': 'change',
  '转变': 'transform',
  '转换': 'convert',
  '转化': 'transform',
  '变成': 'become',
  '成为': 'become',
  '作为': 'as',
  '当作': 'regard as',
  '看作': 'view as',
  '视为': 'consider as',
  '认为': 'think',
  '觉得': 'feel',
  '感觉': 'feel',
  '感到': 'feel',
  '感受': 'experience',
  '体会': 'realize',
  '理解': 'understand',
  '明白': 'understand',
  '了解': 'know',
  '认识': 'know',
  '知道': 'know',
  '记得': 'remember',
  '忘记': 'forget',
  '想起': 'recall',
  '想到': 'think of',
  '认为': 'believe',
  '相信': 'believe',
  '信任': 'trust',
  '怀疑': 'doubt',
  '疑问': 'question',
  '问题': 'problem',
  '困难': 'difficulty',
  '麻烦': 'trouble',
  '烦恼': 'worry',
  '担心': 'worry',
  '关心': 'care',
  '关注': 'attention',
  '注意': 'attention',
  '留意': 'pay attention',
  '小心': 'be careful',
  '谨慎': 'be cautious',
  '警惕': 'be vigilant',
  '防止': 'prevent',
  '避免': 'avoid',
  '预防': 'prevention',
  '保护': 'protection',
  '维护': 'maintenance',
  '保养': 'maintenance',
  '保存': 'save',
  '保留': 'retain',
  '保持': 'maintain',
  '维持': 'maintain',
  '持续': 'sustain',
  '坚持': 'persist',
  '坚守': 'hold on',
  '坚定': 'firm',
  '坚决': 'resolute',
  '坚强': 'strong',
  '勇敢': 'brave',
  '大胆': 'bold',
  '谨慎': 'prudent',
  '慎重': 'careful',
  '仔细': 'careful',
  '认真': 'serious',
  '负责': 'responsible',
  '责任': 'responsibility',
  '义务': 'obligation',
  '权利': 'right',
  '利益': 'interest',
  '好处': 'benefit',
  '益处': 'benefit',
  '优势': 'advantage',
  '劣势': 'disadvantage',
  '缺点': 'disadvantage',
  '优点': 'advantage',
  '特色': 'feature',
  '特点': 'characteristic',
  '特征': 'characteristic',
  '特性': 'property',
  '性能': 'performance',
  '功能': 'function',
  '作用': 'effect',
  '用途': 'use',
  '用法': 'usage',
  '使用': 'use',
  '利用': 'utilize',
  '应用': 'apply',
  '运用': 'apply',
  '采用': 'adopt',
  '采取': 'take',
  '选择': 'choose',
  '挑选': 'select',
  '选取': 'select',
  '选用': 'choose',
  '决定': 'decide',
  '确定': 'determine',
  '确认': 'confirm',
  '肯定': 'affirm',
  '否定': 'deny',
  '拒绝': 'refuse',
  '接受': 'accept',
  '同意': 'agree',
  '赞成': 'approve',
  '反对': 'oppose',
  '支持': 'support',
  '帮助': 'help',
  '协助': 'assist',
  '辅助': 'auxiliary',
  '配合': 'cooperate',
  '合作': 'cooperate',
  '协作': 'collaborate',
  '协调': 'coordinate',
  '调节': 'adjust',
  '调整': 'adjust',
  '调节': 'regulate',
  '控制': 'control',
  '管理': 'manage',
  '治理': 'govern',
  '统治': 'rule',
  '领导': 'lead',
  '指导': 'guide',
  '引导': 'guide',
  '指引': 'direct',
  '指挥': 'command',
  '命令': 'order',
  '指示': 'instruct',
  '要求': 'require',
  '需求': 'demand',
  '需要': 'need',
  '必须': 'must',
  '必要': 'necessary',
  '重要': 'important',
  '主要': 'main',
  '次要': 'secondary',
  '再次': 'again',
  '重复': 'repeat',
  '重新': 'again',
  '另外': 'another',
  '其他': 'other',
  '其余': 'rest',
  '剩下': 'remain',
  '剩余': 'remaining',
  '多余': 'extra',
  '额外': 'additional',
  '附加': 'additional',
  '补充': 'supplement',
  '弥补': 'make up',
  '完善': 'perfect',
  '改进': 'improve',
  '改善': 'improve',
  '提高': 'improve',
  '提升': 'promote',
  '增强': 'enhance',
  '加强': 'strengthen',
  '巩固': 'consolidate',
  '稳定': 'stabilize',
  '固定': 'fix',
  '确定': 'determine',
  '决定': 'decide',
  '解决': 'solve',
  '处理': 'handle',
  '应对': 'deal with',
  '对付': 'cope with',
  '克服': 'overcome',
  '战胜': 'defeat',
  '打败': 'defeat',
  '胜利': 'victory',
  '成功': 'success',
  '失败': 'failure',
  '失误': 'mistake',
  '错误': 'error',
  '误差': 'error',
  '偏差': 'deviation',
  '差别': 'difference',
  '差异': 'difference',
  '区别': 'distinction',
  '分别': 'respectively',
  '各自': 'each',
  '各个': 'each',
  '每个': 'every',
  '所有': 'all',
  '全部': 'all',
  '整体': 'whole',
  '整个': 'entire',
  '部分': 'part',
  '局部': 'local',
  '个别': 'individual',
  '单独': 'separate',
  '独立': 'independent',
  '自主': 'autonomous',
  '自动': 'automatic',
  '手动': 'manual',
  '人工': 'manual',
  '半自动': 'semi-automatic',
  '全自动': 'fully automatic',
  '智能': 'intelligent',
  '智慧': 'wisdom',
  '聪明': 'smart',
  '灵活': 'flexible',
  '灵敏': 'sensitive',
  '敏捷': 'agile',
  '迅速': 'quick',
  '快速': 'fast',
  '高速': 'high-speed',
  '加速': 'accelerate',
  '减速': 'decelerate',
  '匀速': 'uniform speed',
  '变速': 'variable speed',
  '高速': 'high speed',
  '低速': 'low speed',
  '中速': 'medium speed',
  '全速': 'full speed',
  '半速': 'half speed',
  '速度': 'speed',
  '速率': 'rate',
  '频率': 'frequency',
  '周期': 'period',
  '间隔': 'interval',
  '间隙': 'gap',
  '距离': 'distance',
  '时间': 'time',
  '时刻': 'moment',
  '时期': 'period',
  '阶段': 'stage',
  '过程': 'process',
  '进程': 'process',
  '进度': 'progress',
  '程度': 'degree',
  '水平': 'level',
  '标准': 'standard',
  '规范': 'norm',
  '规则': 'rule',
  '规定': 'regulation',
  '规矩': 'rule',
  '规律': 'law',
  '原则': 'principle',
  '原理': 'principle',
  '道理': 'reason',
  '理由': 'reason',
  '原因': 'cause',
  '结果': 'result',
  '后果': 'consequence',
  '成果': 'achievement',
  '效果': 'effect',
  '影响': 'influence',
  '作用': 'role',
  '价值': 'value',
  '价格': 'price',
  '成本': 'cost',
  '费用': 'expense',
  '开支': 'expenditure',
  '支出': 'expenditure',
  '收入': 'income',
  '收益': 'revenue',
  '利润': 'profit',
  '盈利': 'profit',
  '亏损': 'loss',
  '损失': 'loss',
  '损害': 'damage',
  '伤害': 'harm',
  '危害': 'hazard',
  '危险': 'danger',
  '风险': 'risk',
  '保险': 'insurance',
  '安全': 'safety',
  '保障': 'guarantee',
  '保证': 'guarantee',
  '确保': 'ensure',
  '确认': 'confirm',
  '证实': 'verify',
  '证明': 'prove',
  '证据': 'evidence',
  '依据': 'basis',
  '根据': 'according to',
  '按照': 'according to',
  '依照': 'in accordance with',
  '遵循': 'follow',
  '遵守': 'observe',
  '符合': 'conform to',
  '满足': 'satisfy',
  '达到': 'achieve',
  '完成': 'complete',
  '实现': 'realize',
  '达成': 'reach',
  '获得': 'obtain',
  '得到': 'get',
  '收到': 'receive',
  '接到': 'receive',
  '受到': 'suffer',
  '遭受': 'suffer',
  '经历': 'experience',
  '经过': 'through',
  '通过': 'pass',
  '超过': 'exceed',
  '超越': 'surpass',
  '胜过': 'surpass',
  '优于': 'better than',
  '强于': 'stronger than',
  '弱于': 'weaker than',
  '低于': 'lower than',
  '高于': 'higher than',
  '大于': 'greater than',
  '小于': 'less than',
  '等于': 'equal to',
  '相当于': 'equivalent to',
  '类似于': 'similar to',
  '相同于': 'same as',
  '不同于': 'different from',
  '区别于': 'distinguished from',
  '分离': 'separate',
  '分开': 'separate',
  '分散': 'disperse',
  '分布': 'distribute',
  '分配': 'allocate',
  '配置': 'configure',
  '安排': 'arrange',
  '布置': 'arrange',
  '部署': 'deploy',
  '设置': 'set',
  '设定': 'set',
  '建立': 'establish',
  '创建': 'create',
  '制造': 'manufacture',
  '生产': 'produce',
  '加工': 'process',
  '处理': 'process',
  '处置': 'dispose',
  '处理': 'handle',
  '办理': 'handle',
  '管理': 'manage',
  '治理': 'govern',
  '统治': 'rule',
  '控制': 'control',
  '掌握': 'grasp',
  '把握': 'seize',
  '抓住': 'catch',
  '抓紧': 'hold tight',
  '放松': 'relax',
  '释放': 'release',
  '解放': 'liberate',
  '开放': 'open',
  '开启': 'open',
  '打开': 'open',
  '关闭': 'close',
  '关上': 'close',
  '封闭': 'seal',
  '密封': 'seal',
  '封锁': 'blockade',
  '禁止': 'prohibit',
  '阻止': 'prevent',
  '阻挡': 'block',
  '阻碍': 'hinder',
  '妨碍': 'impede',
  '干扰': 'interfere',
  '打扰': 'disturb',
  '影响': 'affect',
  '作用': 'act on',
  '效果': 'effect',
  '结果': 'result',
  '成果': 'achievement',
  '后果': 'consequence',
  '效果': 'result',
};

// 执行替换
let count = 0;
for (const [cn, en] of Object.entries(translations)) {
  const regex = new RegExp(cn, 'g');
  const matches = content.match(regex);
  if (matches) {
    count += matches.length;
    content = content.replace(regex, en);
  }
}

fs.writeFileSync(filePath, content, 'utf8');
console.log(`翻译完成，共替换 ${count} 处中文内容`);
